### ISSUE TITLE
tab怎么改变颜色

### ISSUE THREAD

**Issue by SmallProgramIndustry** [nuonuoge/ionic4_angular6_elm#1]
我也是用svg格式。我没怎么用过svg格式，我看你操作是监听tab，但是好像没有对他进行修改操作

**Comment by SmallProgramIndustry** [comment]
感谢您的回答，我想问的是;tab自定义图标改变颜色，我是模仿你的做的、但是做的过程发现，tab自定义图标颜色改变不了。我把ion tab ionc 监听了，改颜色是没有效果的。

然后我看到你公共组件components 的 svg，这个是写了多个svg的图片的代码。您的改变颜色和这个应该息息相关，但是看得不太懂。没用过svg格式的图片。能为我解答一下吗？十分感谢！！！

**Comment by SmallProgramIndustry** [comment]
顺便提问下：@ionic-angular 找不到模块，请问为啥呢？配置文件删除了，再重新下载，一样不行，我看到您用到了

**Comment by nuonuoge** [comment]
你用的是v3版本还是v4版本，v3是ionic-angular，v4则是@ionic/angular

**Comment by SmallProgramIndustry** [comment]
我的版本是V4 ，用的是@ ionic-angular，代码报错说@ ionic-angular找不到模块，配置里面是@ionic/angular": "4.0.0-beta.2   
ion-tab,我会仔细看看V4文档，找找看，感觉也改了挺多东西的哈哈，v3我是用tabicon改变自定义icon的

**Comment by nuonuoge** [comment]
v3和v4变动还是很大的，这是我升级过程中简单总结的，官方也有一个升级讲解，在ionic文档中：http://www.jianshu.com/p/37c1ab91dce0

**Comment by SmallProgramIndustry** [comment]
关注你了。你的 文档总结，是介绍了ionic4 + angular6。没有说详情，详情还是要看源码。我对你的目录构建也是挺喜欢的
