### ISSUE TITLE
请教下一个问题

### ISSUE THREAD

**Issue by UTSOURCE** [nuonuoge/ionic4_angular6_elm#12]
![image](https://user-images.githubusercontent.com/14830459/47138875-1cf99180-d2ed-11e8-9c46-567fc4dfc6ed.png)
我怎么ba把这地方的图标写出动态的

**Comment by nuonuoge** [comment]
svg不支持双向绑定，不过你自己操作dom是可以改的，可以写个指令，把值动态传给指令，改变xlink:href的value
