### ISSUE TITLE
跑不起来 没有加API的baseUrl  项目编译还有两处错误

### ISSUE THREAD

**Issue by semprone** [nuonuoge/ionic4_angular6_elm#14]

**Comment by nuonuoge** [comment]
你是指npm start本地跑不起来还是编译后打包跑不起来，信息太少无法回答

**Comment by semprone** [comment]
http方法（http.get http.post ...)中的url参数都不是完整的url。
![image](https://user-images.githubusercontent.com/28696015/47502684-05954800-d89b-11e8-8068-0c0a0e487b13.png)

**Comment by semprone** [comment]
找到了  原来在代理里面
