### ISSUE TITLE
想请教为何不使用NavController了

### ISSUE THREAD

**Issue by wby3902433** [nuonuoge/ionic4_angular6_elm#15]
现在使用的是angular的router ， 想请教是出于什么考虑为何不使用ionic的NavController了呢 ？

**Comment by nuonuoge** [comment]
1. ng的路由用起来更爽，也没bug，而且可以和pc路由逻辑共用
2. ionic3导航是符合移动原生开发的 push pop堆栈方式的导航栈，只做原生app开发 这种方式是最好用的，不过ionic4为了兼容web路由的线性特点 切换成angular路由了

**Comment by wby3902433** [comment]
是否可以理解为 如果是使用ionic4针对android和ios的开发 ，不考虑h5移动页面之类的， 推荐使用NavController。如果需要兼容制作web页面，使用angular的router 更佳 ？ 因为之前自己是做原生开发的 ，push pop堆栈方式更适应思维 。

**Comment by nuonuoge** [comment]
我个人觉得都可以，完全是看个人喜好，但是我用ionic3 NavController的时候每次调试刷新都回到路由起点，还得一次次再点到要调试的页面
