### ISSUE TITLE
页面切换动画问题

### ISSUE THREAD

**Issue by chenp1204** [nuonuoge/ionic4_angular6_elm#16]
请教下楼主，路由切换默认是没有动画的，你的页面切换动画是自己写的css吗~

**Comment by nuonuoge** [comment]
你是指loading那种动画吗

**Comment by chenp1204** [comment]
是页面切换时的动画，比如从tab页点击进入详情页~

**Comment by nuonuoge** [comment]
1. 页面切换，从右边到左边或者从左边到右边渐入渐出这种？这是ionic自带的
2. 如果是进入页面，水果跳动是自己实现的
