### ISSUE TITLE
关于运行项目的小问题？

### ISSUE THREAD

**Issue by leviduan** [nuonuoge/ionic4_angular6_elm#18]
你好我刚开始学前端的东西，我有个问题请教下你，运行这个项目使用的是npm start这个命令。
我用ionic serve 运行为什么很多数据拉取不下来呢？请问不能通过ionic运行这个项目么？

**Comment by nuonuoge** [comment]
npm start运行的是package.json里面的start，你可以看下package.json，v4版本不再用ionic启动了，v3可以
