### ISSUE TITLE
chrome可以打开，ionic4在百度浏览器报错，什么原因

### ISSUE THREAD

**Issue by chenliao0211** [nuonuoge/ionic4_angular6_elm#19]
截不了图，ionic serve启动后，报错：unexpected token [ 。是什么原因？q:99173113

**Comment by nuonuoge** [comment]
https://angular.cn/guide/browser-support  估计和ng的浏览器支持版本有关，我没用过百度浏览器，不太清楚这块，百度是ie的内核
