### ISSUE TITLE
ionic4 正式版出来了

### ISSUE THREAD

**Issue by UTSOURCE** [nuonuoge/ionic4_angular6_elm#21]
ionic4 正式版出来了
https://blog.ionicframework.com/introducing-ionic-4-ionic-for-everyone/

**Comment by nuonuoge** [comment]
好的，谢谢，近期抽时间升级到正式版去

**Comment by nuonuoge** [comment]
已升级到正式版

**Comment by UTSOURCE** [comment]
大神，厉害，佩服！！！真快！！！能有空搞一个体验地址吗？
