### ISSUE TITLE
你好 我想问一下为什么我新创建的页面使用你的全局组件会报错，求解答

### ISSUE THREAD

**Issue by 1131150140** [nuonuoge/ionic4_angular6_elm#22]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'back-header' is not a known element:
1. If 'back-header' is an Angular component, then verify that it is part of this module.
2. If 'back-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<ion-header>
  [ERROR ->]<back-header hTitle="收货地址"></back-header>
</ion-header>

**Comment by nuonuoge** [comment]
如果你新建的页面不是声明在app.module.ts里面，那么你组件声明所在的module则需要引入SharedModule才可以使用back-header

**Comment by 1131150140** [comment]
好的
