### ISSUE TITLE
请教下屏幕适配的问题

### ISSUE THREAD

**Issue by UTSOURCE** [nuonuoge/ionic4_angular6_elm#23]
我看你用的是你写的rem.js文件 
我可以用
https://github.com/amfe/article/issues/17
这个嘛？
请指点12谢谢！！！

**Comment by nuonuoge** [comment]
当然可以呀，不过你可能需要修改每个样式的rem数值

**Comment by UTSOURCE** [comment]
”可能需要修改每个样式的rem数值“
可以举一个简单的例子嘛？谢谢

**Comment by nuonuoge** [comment]
https://github.com/amfe/lib-flexible/tree/master 官网有写：如果你觉得移动端适配让人头疼，建议采用最新适配方案：https://www.w3cplus.com/css/vw-for-layout.html
flexible的rem方案根据dpr的值来修改html的font-size，从而使用rem实现等比缩放，我这个项目里面的rem.js计算和flexible是不一样的，比如图片width:3rem;在flexible下可能你就需要做调整，3rem可能不是你设计稿的效果

**Comment by UTSOURCE** [comment]
那在使用你的项目里面的rem.js的情况下
我设计图是750px的苹果6的设计图，100px*100px的块，转换成rem是多少？

**Comment by nuonuoge** [comment]
我这个项目里的方案并不好，因为是个demo，所以也没有特别在意适配这块，是以320和12px为基准的，然后根据当前设备浏览器的clientwidth/320*12简单粗暴计算的。以750px这个设计图看的话，iPhone6的设备宽度和高度为375pt * 667pt，375/320*12=14.0625; 建议你还是直接上flexible推荐的vw方案

**Comment by UTSOURCE** [comment]
ok
