### ISSUE TITLE
服务器渲染的问题

### ISSUE THREAD

**Issue by UTSOURCE** [nuonuoge/ionic4_angular6_elm#24]
新年好！！！
ionic4 可以服务器渲染的吗？
方便seo收录。
不行的话有啥建议吗？

**Comment by nuonuoge** [comment]
https://github.com/ionic-team/ionic/issues/15041  貌似还木有
阿里这个暂时也不支持SSR: https://github.com/NG-ZORRO/ng-zorro-antd-mobile

**Comment by UTSOURCE** [comment]
好的谢谢！！！
