### ISSUE TITLE
大佬问你个问题呗

### ISSUE THREAD

**Issue by UTSOURCE** [nuonuoge/ionic4_angular6_elm#25]
<ion-icon src="assets/svg/search.svg" color="light"></ion-icon>

  <svg class="arrow_right" [routerLink]="['/city', guessCityId]">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#arrow-right"></use>
      </svg>

大佬，为啥不用上面一种svg啊？为啥搞成代码的，指点下，谢谢，用代码的好些吗？

**Comment by nuonuoge** [comment]
上面一种svg是啥意思？其实这块不用svg，用iconfont生成svg格式的库更好，有图形界面方便维护，扩展图标

**Comment by UTSOURCE** [comment]
我上面写的指  <ion-icon src="assets/tabs/message.svg"></ion-icon>
这么写，我看你的 <svg fill="#333" class="arrow_right">
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#arrow-right"></use>
                  </svg>



![image](https://user-images.githubusercontent.com/14830459/53776338-b938d380-3f30-11e9-8010-79d04b901384.png)

**Comment by nuonuoge** [comment]
其实没啥区别，当时这么写是因为这块参考了别人的项目，他正好搞了个svg文件，里面实现了很多图标，我也就懒得去整这一堆图标了，你这个写法还是需要自己搞一堆svg图片过来的

**Comment by UTSOURCE** [comment]
ok，知道了

**Comment by UTSOURCE** [comment]
谢谢！！！
