### ISSUE TITLE
网络请求没有设置base url，打包到真机后，请求失败

### ISSUE THREAD

**Issue by dongshan1986** [nuonuoge/ionic4_angular6_elm#27]
npm start可以配置proxy，能够正常在Chrome运行
网络请求没有设置base url，打包到真机后，直接请求的localhost，请求失败，难道要一个一个改网络请求，有什么快捷方案吗？

**Comment by dongshan1986** [comment]
批量替换解决了

**Comment by dongshan1986** [comment]
改完以后发现，真机一直报验证码失效，console里面没有任何报错

**Comment by nuonuoge** [comment]
1.批量替换这个可以在拦截器HttpInterceptor里面搞，也可以在environments里面配置读取，等不忙了我改下加上类似配置
2.验证码这个我没有验证过

**Comment by nuonuoge** [comment]
我加了拦截器，打包时请求已解决
