### ISSUE TITLE
模拟器上调不通接口

### ISSUE THREAD

**Issue by Cheng007** [nuonuoge/ionic4_angular6_elm#28]
你好，我这边启动了项目，
发现在安卓真机运行没问题，但在安卓模拟器中接口调不通，
如下图：

![image](https://user-images.githubusercontent.com/13946264/57978025-ff350c00-7a36-11e9-8ac0-7f448ddc3ce1.png)

请问这个问题怎么解决？
感谢

**Comment by nuonuoge** [comment]
这个我不太了解，平时不搞模拟器，爱莫能助了

**Comment by ren1151576** [comment]
看一下是不是android9.0的问题
