### ISSUE TITLE
ionic 生成 android  app 无法请求网络 

### ISSUE THREAD

**Issue by wuhuaqing** [nuonuoge/ionic4_angular6_elm#29]
![image](https://user-images.githubusercontent.com/9549867/59262665-3d0e0480-8c72-11e9-87ef-d5cf94cd76ab.png)

使用你的应用生成android app，登录时没有网络请求，验证码也拉不到，应该是没有HTTP请求，求解！

**Comment by nuonuoge** [comment]
https://github.com/nuonuoge/ionic4_angular6_elm/issues/28 有时候后端接口不通，我看这个在真机上是通的
