### ISSUE TITLE
ionic4 生命周期

### ISSUE THREAD

**Issue by SmallProgramIndustry** [nuonuoge/ionic4_angular6_elm#3]
我在看文档的过程，也看你项目，好像没有用到ionic4的生命周期了。请问怎么使用ionic4的生命周期

**Comment by nuonuoge** [comment]
v3版本在二级菜单隐藏tabs用过一些，v4里面我不清楚你想问的生命周期含义，oninit等也属于ng的生命周期勾子之一呀，这个很多文件都会用到，只是项目中没有应用到全部周期勾子

**Comment by SmallProgramIndustry** [comment]
你好，我想了解的是。ionic的生命周期，angular的生命周期也有，但是没有ionic的生命周期完善。[ionic3的生命周期网站](https://ionicframework.com/docs/api/navigation/NavController/)ionic4后，生命周期就失效了。很神奇。

**Comment by SmallProgramIndustry** [comment]
但是angular的生命周期是有检测功能，这个就非常厉害了

**Comment by nuonuoge** [comment]
nav在v4我觉得已经用不上了，v4已经全面向ng靠拢，使用ng的路由，自然生命周期钩子也就使用ng配套的api，不知道你说的不如ionic生命周期完善是哪几个，ionViewDidLoad，ionViewWillEnter，ionViewDidEnter，ionViewWillLeave，ionViewDidLeave，ionViewWillUnload这些用ng路由的生命周期钩子完全可以hold住，ionViewCanEnter和ionViewCanLeave也可以用ng的路由守卫实现

**Comment by SmallProgramIndustry** [comment]
是这样的，当时，我测试的时候，发现数据在ng的生命周期赋值不到，是组件更新后，ng才检测。后来发现，原来是我代码的问题。

请教一下，ionic4插件问题ionic v3 app.module.ts => providers 声明
ionic v4的文档也是app.module.ts => providers 声明，但是抛出 plugin Object(...) is not a function，使用不了插件的问题，请问您是怎么在ionic4中使用插件的问题呢？/感谢！

**Comment by nuonuoge** [comment]
不太理解你说的插件啥意思，providers是用来搞依赖注入的，v3和v4并木有什么变化，怀疑你代码写的有问题

**Comment by SmallProgramIndustry** [comment]
https://beta.ionicframework.com/docs/native/app-update 就比如说这个插件，我按照这里的一步一步做的，请问您的项目有安装插件吗？我去看下代码就懂了。请指点一下

**Comment by nuonuoge** [comment]
必须用app-update 5.0以上版本，4.0不行，以你那个为例，安装时候默认安装4.0版本，所以你必须指定版本：
npm install @ionic-native/app-update@5.0.0-beta.14
然后用的时候必须带/ngx
import { AppUpdate } from '@ionic-native/app-update/ngx';

**Comment by SmallProgramIndustry** [comment]
受教了，6666666，您是怎么知道的呢？我看文档虽然不算非常仔细，但是我没看到关于插件的介绍

**Comment by nuonuoge** [comment]
额，我也是查的，官方issues里面有解释😊

**Comment by SmallProgramIndustry** [comment]
可是我去看版本问题的时候好像都没有说有测试版呀https://github.com/apache/cordova-plugin-camera/releases，例如这个相机插件

**Comment by SmallProgramIndustry** [comment]
https://github.com/apache/cordova-plugin-camera/releases

**Comment by SmallProgramIndustry** [comment]
我懂了，整个ionic的项目都是@5.0.0-beta.14,所以安装的插件都是这样测试版
