### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by chysx** [nuonuoge/ionic4_angular6_elm#30]
你好，大神，我npm install报错：
![image](https://user-images.githubusercontent.com/3417576/60427337-13b91680-9c29-11e9-803b-1a411556580e.png)

**Comment by nuonuoge** [comment]
你这是windows上安装node-sass的问题，node-sass和nodejs的版本也有关，网上很多解决方案

**Comment by chysx** [comment]
好的，谢谢大佬
