### ISSUE TITLE
build之后部署到nginx，登陆时一直提示验证码失效，且返回按钮也失效

### ISSUE THREAD

**Issue by Howar6htb** [nuonuoge/ionic4_angular6_elm#32]
build之后部署到nginx，登陆时一直提示验证码失效，且返回按钮也失效，请问是怎么回事呢

**Comment by nuonuoge** [comment]
你把environment.prod.ts里面的apiUrl改成''， 然后在nginx配置时，把请求转到http://cangdu.org:8001试一下

**Comment by Howar6htb** [comment]
好的，谢谢
