### ISSUE TITLE
官网的文档似乎没有区分5和6

### ISSUE THREAD

**Issue by Lyfei** [nuonuoge/ionic4_angular6_elm#36]
只有3，4，当前。
那6和5是不是基本一致

**Comment by nuonuoge** [comment]
嗯 类比angular的版本变化

**Comment by Lyfei** [comment]
> 嗯 类比angular的版本变化

好的，还想请教下ionic的版本升级。我看你从3升到4的时候修改时间经历了两周，是不是升级了ionic的包版本，但是项目里基于旧版本的代码全得自己手动修改成新的写法？包括目录结构等

**Comment by nuonuoge** [comment]
@Lyfei  github居然没有消息提醒··· ionic从3开始版本升级比较友好了 就像angular2到最新版本 其实官方也提供了相应的升级命令 其实改动并不大

**Comment by Lyfei** [comment]
7 还有兴趣升级吗？大环境似乎都转向uni了

**Comment by nuonuoge** [comment]
> 7 还有兴趣升级吗？大环境似乎都转向uni了

不计划升级了，国内angular市场越来越小了
