### ISSUE TITLE
如何实现定位呢求分享

### ISSUE THREAD

**Issue by zhiwo** [nuonuoge/ionic4_angular6_elm#7]

**Comment by nuonuoge** [comment]
这个要后台搞定，百度和腾讯都有api，但是每日访问量是受限的，你感兴趣的话点击页面上的后台传送地址，读读后端代码

**Comment by zhiwo** [comment]
> 这个要后台搞定，百度和腾讯都有api，但是每日访问量是受限的，你感兴趣的话点击页面上的后台传送地址，读读后端代码

如果后台实现，那前台岂不是只能通过经纬度定位了？后台通过ip定位？不准吧

**Comment by nuonuoge** [comment]
IP地址段 (IP Geolocation)，获取城市级别(City-level)的位置信息

GPS, 如果有硬件支持, 就直接卫星定位

Wi-Fi/基站，通过搜索你附近的Wi-Fi AP (Access Point)，再根据每个AP信号强弱进行三角定位。 AP的位置事先通过主动或者众包的方式采集，比如Android设备会默认开启后台Wi-Fi扫描，谷歌的街景车也会沿路扫描Wi-Fi接入点，还有之前爆出的Apple泄露用户位置信息，其实也是匿名的Wi-Fi扫描，这些都是当设备接收到可靠GPS信号时，上传当前位置的Wi-Fi信息，包括MAC，信号强度等。

方式就是通过以上的手段，如果没有gps，就通过wifi或者通讯信号基站来搞了，具体算法我就不清楚了
