### ISSUE TITLE
ionic cordaova run android

### ISSUE THREAD

**Issue by SmallProgramIndustry** [nuonuoge/ionic4_angular6_elm#8]
打包到安装手机的过程，完好的打包到手机了，但是一直白屏，看不到页面。
我的ionic info
Ionic:-------------------------------------------------------------------------

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\ASUS\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 3 other plugins)

System:

   NodeJS : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.0
   OS     : Windows 10
,

**Comment by SmallProgramIndustry** [comment]
我翻墙没了，所以进不了谷歌真机调试页面，很无奈 唉.......

**Comment by nuonuoge** [comment]
肯定白屏啊，proxy配置我只搞了dev的，prod木有哦，相当于prod所有的ajax请求都是失败，这个你查查文档看看v4怎么设置，我打算等正式版出来再搞来着，现在组件一堆bug，比如input的clear就不好使

**Comment by SmallProgramIndustry** [comment]
proxy还要配置吗？不是ionic帮忙配置好的吗？.....v3都是直接用的。
我创建一个新的应用能直接打包到手机。但是没有实时调试，写了一堆代码，打包就报错了
https://beta.ionicframework.com/docs/api/input 
 找到属性clearInput开启就可以了

**Comment by SmallProgramIndustry** [comment]
我脑子秀逗了，是要配置的

**Comment by SmallProgramIndustry** [comment]
代理是不是要自己搞个服务器做代理？

**Comment by nuonuoge** [comment]
不需要，因为文件都打包到本地了，这种本地加载都不需要懒加载（因为文件都在本地，就是个读硬盘速度），然后本地文件可以直接ajax请求，简单粗暴点的方式就是直接所有请求的url替换成带ip端口协议的url

**Comment by SmallProgramIndustry** [comment]
????????????????????????????????
我对代理这个没怎么接触，就了解过请求头，做跨域
我有点懵逼。我是直接用ionic4+angular6写的，请求是leancloud做后端。
请问怎么解决呢？

**Comment by SmallProgramIndustry** [comment]
请教一下，你有做过图片保存到相册吗？我现在用的那个插件，ios反应非常慢，android也要3~4秒

**Comment by SmallProgramIndustry** [comment]
用v3版本的Photo Library保存的
